services:
  user:
    base-url: http://user-service:8080
  product:
    base-url: http://product-service:8081

management:
  otlp:
    metrics:
      export:
        url: http://otel-collector:4318/v1/metrics
        step: 15s
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://otel-collector:4318/v1/traces
